name: Generate

on: 
  workflow_dispatch:
    inputs:
      book:
        required: true
        default: directory
        description: Book directory

jobs:
  pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: retrieve chapters
        id: chapters
        run: |
          mkdir output
          echo "files=$(printf '"%s" ' $(find ${{ github.event.inputs.book }} -name '*.md'))" > $GITHUB_OUTPUT

      - uses: docker://pandoc/latex:3.1
        with:
          args: >-
            --standalone
            --output=output/${{ github.event.inputs.book }}.epub
            ${{ github.event.inputs.book }}/title.txt
            ${{ steps.chapters.outputs.files }}
          
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output